//! `Mingling` Example - Dispatch Tree
//!
//! # How to Deploy
//! 1. Enable the `dispatch_tree` feature (`comp` is optional)
//! ```toml
//! mingling = { version = "...", features = [
//!     "dispatch_tree",  // Enable this feature
//!     "comp" // optional
//! ] }
//! ```
//!
//! 2. Using `cargo expand`:
//!
//! ```bash
//! cargo expand --manifest-path examples/example-dispatch-tree/Cargo.toml > expanded.rs
//! cat expanded.rs
//! ```

#![allow(unused_mut)]

use mingling::prelude::*;

fn main() {
    let mut program = ThisProgram::new();

    // // After enabling `dispatch_tree`, this method will no longer exist
    // program.with_dispatcher(CommandGreet);
    //
    // // The `CompletionDispatcher` automatically generated by `comp` will also be imported automatically
    // program.with_dispatcher(CompletionDispatcher);

    program.exec();
}

dispatcher!("greet", CommandGreet => EntryGreet);
dispatcher!("help", CommandHelp => EntryHelp);
dispatcher!("quit", CommandQuit => EntryQuit);
dispatcher!("list", CommandList => EntryList);
dispatcher!("status", CommandStatus => EntryStatus);
dispatcher!("save", CommandSave => EntrySave);
dispatcher!("load", CommandLoad => EntryLoad);
dispatcher!("config", CommandConfig => EntryConfig);
dispatcher!("run", CommandRun => EntryRun);
dispatcher!("debug", CommandDebug => EntryDebug);
dispatcher!("version", CommandVersion => EntryVersion);

gen_program!();
